server {
    listen 3002;
    server_name thinkmtb.moralesrodionoff.com;
    return 301 https://$host:3000$request_uri;
}

server {
    listen 3000 ssl;
    server_name thinkmtb.moralesrodionoff.com;

    ssl_certificate /opt/homebrew/etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /opt/homebrew/etc/nginx/certs/selfsigned.key;

    # If someone hits this HTTPS port with plain HTTP, show a redirect page
    error_page 497 @http_to_https;
    location @http_to_https {
        return 301 https://$host:3000$request_uri;
    }

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
