#!/bin/bash

##############################################################################
# Nginx Reverse Proxy & SSL Setup Script
# 
# Sets up Nginx as a reverse proxy for the Node.js application
# Handles SSL/TLS with Let's Encrypt
# Supports subdomain routing for multi-tenancy
#
# Usage: ./setup-nginx-ssl.sh --domain yourdomain.com --email your@email.com
##############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DOMAIN=""
EMAIL=""
APP_PORT=3000
APP_USER="appuser"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --domain)
      DOMAIN="$2"
      shift 2
      ;;
    --email)
      EMAIL="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Helper functions
log_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
  echo -e "${GREEN}✓${NC} $1"
}

log_error() {
  echo -e "${RED}✗${NC} $1"
}

log_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

# Validate inputs
if [ -z "$DOMAIN" ]; then
  log_error "Domain is required. Usage: ./setup-nginx-ssl.sh --domain yourdomain.com --email your@email.com"
  exit 1
fi

if [ -z "$EMAIL" ]; then
  log_error "Email is required for Let's Encrypt. Usage: ./setup-nginx-ssl.sh --domain yourdomain.com --email your@email.com"
  exit 1
fi

# Check if running as non-root with sudo
# Allow root for VPS deployments where root is the primary user
if [[ $EUID -eq 0 ]]; then
  # Running as root - this is acceptable for initial VPS setup
  # The script will run commands directly instead of using sudo
  SUDO=""
else
  # Running as non-root - use sudo for privileged commands
  SUDO="sudo"
fi

# Install Nginx
install_nginx() {
  log_info "Installing Nginx..."
  
  if command -v nginx &> /dev/null; then
    NGINX_VERSION=$(nginx -v 2>&1)
    log_success "Nginx already installed: $NGINX_VERSION"
  else
    $SUDO apt-get update -qq
    $SUDO apt-get install -y nginx nginx-common &>/dev/null
    log_success "Nginx installed"
  fi
  
  # Enable Nginx to start on boot
  $SUDO systemctl enable nginx
}

# Install Certbot for SSL
install_certbot() {
  log_info "Installing Certbot for Let's Encrypt..."
  
  if command -v certbot &> /dev/null; then
    CERTBOT_VERSION=$(certbot --version)
    log_success "Certbot already installed: $CERTBOT_VERSION"
  else
    $SUDO apt-get install -y certbot python3-certbot-nginx &>/dev/null
    log_success "Certbot installed"
  fi
}

# Create Nginx configuration
create_nginx_config() {
  log_info "Creating Nginx configuration for $DOMAIN..."
  
  # Create sites-available config
  NGINX_CONFIG="/etc/nginx/sites-available/$DOMAIN"
  
  cat > /tmp/nginx-$DOMAIN.conf << 'EOF'
# Redirect all HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name DOMAIN_PLACEHOLDER *.DOMAIN_PLACEHOLDER;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    location / {
        return 301 https://$host$request_uri;
    }
}

# Main HTTPS server block with subdomain support
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name DOMAIN_PLACEHOLDER *.DOMAIN_PLACEHOLDER;
    
    # SSL certificates (will be generated by certbot)
    ssl_certificate /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN_PLACEHOLDER/privkey.pem;
    
    # SSL configuration (modern, secure)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    
    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    
    # Gzip compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript 
               application/json application/javascript application/xml+rss 
               application/rss+xml font/truetype font/opentype 
               application/vnd.ms-fontobject image/svg+xml;
    
    # Logging
    access_log /var/log/nginx/DOMAIN_PLACEHOLDER_access.log combined;
    error_log /var/log/nginx/DOMAIN_PLACEHOLDER_error.log;
    
    # Root location
    root /var/www/html;
    
    # Proxy to Node.js application
    location / {
        proxy_pass http://localhost:APP_PORT_PLACEHOLDER;
        proxy_http_version 1.1;
        
        # Essential headers for proxying
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Disable buffering for real-time features
        proxy_buffering off;
    }
    
    # Static files (if needed)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
EOF
  
  # Replace placeholders
  sed "s/DOMAIN_PLACEHOLDER/$DOMAIN/g; s/APP_PORT_PLACEHOLDER/$APP_PORT/g" /tmp/nginx-$DOMAIN.conf | $SUDO tee $NGINX_CONFIG > /dev/null
  
  log_success "Nginx configuration created"
}

# Enable Nginx site
enable_nginx_site() {
  log_info "Enabling Nginx site..."
  
  NGINX_CONFIG="/etc/nginx/sites-available/$DOMAIN"
  NGINX_ENABLED="/etc/nginx/sites-enabled/$DOMAIN"
  
  if [ ! -L "$NGINX_ENABLED" ]; then
    $SUDO ln -s "$NGINX_CONFIG" "$NGINX_ENABLED"
  fi
  
  # Test Nginx configuration
  log_info "Testing Nginx configuration..."
  if $SUDO nginx -t &>/dev/null; then
    log_success "Nginx configuration is valid"
  else
    log_error "Nginx configuration test failed:"
    $SUDO nginx -t
    exit 1
  fi
  
  # Reload Nginx
  $SUDO systemctl reload nginx
  log_success "Nginx reloaded"
}

# Create certbot directories
setup_certbot_dirs() {
  log_info "Setting up certbot directories..."
  
  $SUDO mkdir -p /var/www/certbot
  $SUDO chown -R www-data:www-data /var/www/certbot
  
  log_success "Certbot directories created"
}

# Generate SSL certificate
generate_ssl_certificate() {
  log_info "Generating SSL certificate with Let's Encrypt..."
  log_info "This may take a moment..."
  
  # Check if certificate already exists
  if [ -d "/etc/letsencrypt/live/$DOMAIN" ]; then
    log_success "Certificate already exists for $DOMAIN"
    return
  fi
  
  # Generate certificate
  $SUDO certbot certonly --nginx \
    -d "$DOMAIN" \
    -d "*.$DOMAIN" \
    -d "admin.$DOMAIN" \
    --email "$EMAIL" \
    --agree-tos \
    --non-interactive \
    --quiet
  
  if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    log_success "SSL certificate generated successfully"
  else
    log_error "Failed to generate SSL certificate"
    exit 1
  fi
}

# Setup certificate auto-renewal
setup_cert_renewal() {
  log_info "Setting up automatic certificate renewal..."
  
  # Add renewal timer to crontab
  CRON_JOB="0 3 * * * /usr/bin/certbot renew --quiet --post-hook \"systemctl reload nginx\""
  
  if $SUDO crontab -l 2>/dev/null | grep -q "certbot renew"; then
    log_success "Certificate renewal already scheduled"
  else
    ($SUDO crontab -l 2>/dev/null; echo "$CRON_JOB") | $SUDO crontab -
    log_success "Certificate renewal scheduled for daily at 3 AM"
  fi
}

# Verify application is running
verify_app() {
  log_info "Verifying application is running on port $APP_PORT..."
  
  if curl -s http://localhost:$APP_PORT > /dev/null 2>&1; then
    log_success "Application is responding on localhost:$APP_PORT"
  else
    log_warning "Application not responding on localhost:$APP_PORT yet"
    log_warning "This may be normal if the app is still starting"
  fi
}

# Print summary
print_summary() {
  echo ""
  echo "╔════════════════════════════════════════════════════════════════╗"
  echo "║    Nginx & SSL Setup Complete! 🎉                             ║"
  echo "╚════════════════════════════════════════════════════════════════╝"
  echo ""
  echo "📊 Configuration Summary:"
  echo "  Domain: $DOMAIN"
  echo "  App Port: $APP_PORT"
  echo "  SSL Certificate: /etc/letsencrypt/live/$DOMAIN/fullchain.pem"
  echo "  Nginx Config: /etc/nginx/sites-available/$DOMAIN"
  echo ""
  echo "🔒 Access Your Application:"
  echo "  User Portal: https://$DOMAIN"
  echo "  Admin Portal: https://admin.$DOMAIN/platform-admin/login"
  echo "  Any Subdomain: https://yourteam.$DOMAIN"
  echo ""
  echo "🔄 Traffic Flow:"
  echo "  Browser → Nginx (443/HTTPS) → Node.js (localhost:$APP_PORT)"
  echo ""
  echo "📝 Important Next Steps:"
  echo "  1. Update DNS at GoDaddy:"
  echo "     A Record: $DOMAIN → 74.208.132.71"
  echo "     CNAME: *.$DOMAIN → $DOMAIN"
  echo ""
  echo "  2. Verify Nginx status:"
  echo "     sudo systemctl status nginx"
  echo ""
  echo "  3. View Nginx logs:"
  echo "     sudo tail -f /var/log/nginx/${DOMAIN}_access.log"
  echo "     sudo tail -f /var/log/nginx/${DOMAIN}_error.log"
  echo ""
  echo "  4. Test HTTPS connectivity:"
  echo "     curl -I https://$DOMAIN"
  echo ""
  echo "✅ SSL Certificate Auto-Renewal:"
  echo "  Certificate will auto-renew 30 days before expiry"
  echo "  Check renewal: sudo certbot renew --dry-run"
  echo ""
}

# Main execution
main() {
  log_info "Starting Nginx & SSL setup for $DOMAIN..."
  echo ""
  
  install_nginx
  install_certbot
  setup_certbot_dirs
  create_nginx_config
  enable_nginx_site
  generate_ssl_certificate
  setup_cert_renewal
  verify_app
  print_summary
  
  log_success "All done! Your app is now served via HTTPS 🚀"
}

# Run main function
main
